language: go

go:
 - 1.9.x

before_script:
  - curl -Lo /usr/local/bin/swagger https://github.com/go-swagger/go-swagger/releases/download/0.13.0/swagger_linux_amd64
  - chmod +x /usr/local/bin/swagger

script:
  - go get -u github.com/golang/dep/cmd/dep
  - make
