sudo: required

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
    - DOCKER_REG=vterdunov
    - PROJECT_NAME=janna-api

language: go

go:
  - 1.9.x
  - 1.10.x

install:
  - o get -u gopkg.in/alecthomas/gometalinter.v2
  - gometalinter.v2 --install
  - go get -u github.com/golang/dep/cmd/dep

script:
  - make

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      make push;
      make push TAG=latest;
    fi
  - if [ -n "$TRAVIS_TAG" ]; then
      make push TAG=$TRAVIS_TAG;
    fi
