---
version: '2'

services:
  redis:
    image: redis:3.2-alpine
    env_file: ../.env
    ports:
      - '6379:6379'
    logging:
      driver: none

  janna: &janna
    build:
      context: ../
      dockerfile: build/Dockerfile.dev
    env_file: ../.env
    ports:
      - '8080:8080'
    depends_on:
      - 'redis'
    # dns:
    #   - 10.0.0.10
    #   - 8.8.8.8
