---
version: '2'

services:
  redis:
    image: redis:3.2-alpine
    env_file: ../.env
    restart: unless-stopped
    ports:
    - '6379:6379'
    container_name: janna-redis
    logging:
      driver: none

  janna:
    build:
      context: ../
      dockerfile: build/Dockerfile.dev
    env_file: ../.env
    restart: unless-stopped
    volumes:
    - ..:/go/src/github.com/vterdunov/janna-api
    container_name: janna-api
    ports:
    - '8081:8081'
    depends_on:
    - 'redis'
